project:
    type: book
    output-dir: ../build

book:
    title: "DocumenterQuarto"
    author: 
        name: "Joey Carpinelli"
        email: "joey@loopy.codes"
    date: "2024-12-31"
    chapters:
        - index.md
        - api/index.qmd 
    sidebar: 
        search: true

toc-title: "Table of Contents"

execute:
    echo: false
    output: true
    cache: false
    freeze: false

bibliography: references.bib

format:
    html:
        theme:
            light: flatly
            dark: darkly
