project:
  type: book

book:
  title: "DocumenterQuarto.jl"
  author: "Joseph D Carpinelli"
  date: "4/28/2024"
  chapters:
    - index.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
    number-depth: 2
    toc-depth: 2
  pdf:
    documentclass: extarticle
    classoption: 14pt


