project:
  type: website

website:
  title: "QuartoDocumenter.jl"
  bread-crumbs: false
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    search: true
    contents:
      - section: "Overview"
        contents:
          - index.qmd
      - section: "Examples"
        contents:
          - examples/index.qmd
      - section: "Reference"
        contents:
          - reference/index.qmd

execute: 
  cache: false
  freeze: false
  echo: true
  output: true
  warning: false

format:
  html:
    theme: 
      light: lightly
      dark: darkly
    css: styles.css
    toc: true



